parallel -vk  ::: \
'python video2images_ref.py --num 0' \
'python video2images_ref.py --num 1' \
'python video2images_ref.py --num 2' \
'python video2images_ref.py --num 3' \
'python video2images_ref.py --num 4' \
'python video2images_ref.py --num 5' \
'python video2images_ref.py --num 6' \
'python video2images_ref.py --num 7' \
'python video2images_ref.py --num 8' \
'python video2images_ref.py --num 9' \
'python video2images_ref.py --num 10' \
'python video2images_ref.py --num 11' \
'python video2images_ref.py --num 12' \
'python video2images_ref.py --num 13' \
'python video2images_ref.py --num 14' \
'python video2images_ref.py --num 15' \
'python video2images_ref.py --num 16' \
'python video2images_ref.py --num 17' \
'python video2images_ref.py --num 18' \
'python video2images_ref.py --num 19' \
'python video2images_ref.py --num 20' \
'python video2images_ref.py --num 21' \
'python video2images_ref.py --num 22' \
'python video2images_ref.py --num 23' \
'python video2images_ref.py --num 24' \
'python video2images_ref.py --num 25' \
'python video2images_ref.py --num 26' \
'python video2images_ref.py --num 27' \
'python video2images_ref.py --num 28' \
'python video2images_ref.py --num 29' \
'python video2images_ref.py --num 30' \
'python video2images_ref.py --num 31' \
'python video2images_ref.py --num 32' \
'python video2images_ref.py --num 33' \
'python video2images_ref.py --num 34' \
'python video2images_ref.py --num 35' \
'python video2images_ref.py --num 36' \
'python video2images_ref.py --num 37' \
'python video2images_ref.py --num 38' \
'python video2images_ref.py --num 39' \
'python video2images_ref.py --num 40' \
'python video2images_ref.py --num 41' \
'python video2images_ref.py --num 42' \
'python video2images_ref.py --num 43' \
'python video2images_ref.py --num 44' \
'python video2images_ref.py --num 45' \
'python video2images_ref.py --num 46' \
'python video2images_ref.py --num 47' \
'python video2images_ref.py --num 48' \
'python video2images_ref.py --num 49' \
'python video2images_ref.py --num 50' \
'python video2images_ref.py --num 51' \
'python video2images_ref.py --num 52' \
'python video2images_ref.py --num 53' \
'python video2images_ref.py --num 54' \
'python video2images_ref.py --num 55' \
'python video2images_ref.py --num 56' \
'python video2images_ref.py --num 57' \
'python video2images_ref.py --num 58' \
'python video2images_ref.py --num 59' \
'python video2images_ref.py --num 60' \
'python video2images_ref.py --num 61' \
'python video2images_ref.py --num 62' \
'python video2images_ref.py --num 63' \
'python video2images_ref.py --num 64' \
'python video2images_ref.py --num 65' \
'python video2images_ref.py --num 66' \
'python video2images_ref.py --num 67' \
'python video2images_ref.py --num 68' \
'python video2images_ref.py --num 69' \
'python video2images_ref.py --num 70' \
'python video2images_ref.py --num 71' \
'python video2images_ref.py --num 72' \
'python video2images_ref.py --num 73' \
'python video2images_ref.py --num 74' \
'python video2images_ref.py --num 75' \
'python video2images_ref.py --num 76' \
'python video2images_ref.py --num 77' \
'python video2images_ref.py --num 78' \
'python video2images_ref.py --num 79' \
'python video2images_ref.py --num 80' \
'python video2images_ref.py --num 81' \
'python video2images_ref.py --num 82' \
'python video2images_ref.py --num 83' \
'python video2images_ref.py --num 84' \
'python video2images_ref.py --num 85' \
'python video2images_ref.py --num 86' \
'python video2images_ref.py --num 87' \
'python video2images_ref.py --num 88' \
'python video2images_ref.py --num 89' \
'python video2images_ref.py --num 90' \
'python video2images_ref.py --num 91' \
'python video2images_ref.py --num 92' \
'python video2images_ref.py --num 93' \
'python video2images_ref.py --num 94' \
'python video2images_ref.py --num 95' \
'python video2images_ref.py --num 96' \
'python video2images_ref.py --num 97' \
'python video2images_ref.py --num 98' \
'python video2images_ref.py --num 99'
